# Generated by Django 4.1.1 on 2022-09-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_alter_article_options_article_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Гость', max_length=30, verbose_name='имя автора')),
                ('text', models.TextField(default='', verbose_name='текст комментария')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Запись')),
            ],
        ),
    ]
