# Generated by Django 4.1.1 on 2022-09-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарий'},
        ),
    ]
