# Generated by Django 4.1.1 on 2022-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('full_text', models.TextField(verbose_name='текст')),
                ('creation_date', models.DateTimeField(verbose_name='дата создания')),
                ('preview', models.ImageField(upload_to='', verbose_name='превью')),
            ],
        ),
    ]
