# Generated by Django 4.1.1 on 2022-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, upload_to='', verbose_name='превью'),
        ),
    ]
