# Generated by Django 4.1.1 on 2022-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, upload_to='blog/imgs', verbose_name='превью'),
        ),
    ]
