# Generated by Django 4.1.1 on 2022-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_creation_date_alter_article_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активное'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='blog/imgs', verbose_name='превью'),
        ),
    ]
