# Generated by Django 4.1.1 on 2022-09-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views_count',
        ),
    ]
