# Generated by Django 4.1.1 on 2022-09-19 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='текст'),
        ),
    ]
