# Generated by Django 4.1.1 on 2022-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('image', models.ImageField(blank=True, default='', upload_to='blog/imgs', verbose_name='фото')),
                ('times_eaten', models.IntegerField(verbose_name='Сколько раз поели')),
                ('last_time_eaten', models.DateTimeField(blank=True, verbose_name='последний раз ели')),
                ('active', models.BooleanField(default=True, verbose_name='активное')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
