# Generated by Django 4.1.1 on 2022-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodmenu',
            name='times_eaten',
            field=models.IntegerField(default=0, verbose_name='Сколько раз поели'),
        ),
    ]
