# Generated by Django 4.1.1 on 2022-09-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodmenu', '0002_alter_prodmenu_times_eaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdmenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип')),
            ],
        ),
        migrations.RemoveField(
            model_name='prodmenu',
            name='type',
        ),
        migrations.AddField(
            model_name='prodmenu',
            name='type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='prodmenu.prodmenutype'),
            preserve_default=False,
        ),
    ]
