# Generated by Django 4.1.1 on 2022-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodmenu', '0003_prodmenutype_remove_prodmenu_type_prodmenu_type_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodmenutype',
            options={'verbose_name': 'Тип еды', 'verbose_name_plural': 'Типы еды'},
        ),
        migrations.AlterField(
            model_name='prodmenu',
            name='last_time_eaten',
            field=models.DateField(default='2000-01-01', verbose_name='последний раз ели'),
        ),
    ]
