# Generated by Django 4.1.1 on 2022-09-22 10:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('nik', models.CharField(max_length=15, verbose_name='Ник')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='blog/imgs', verbose_name='Аватар')),
                ('kontakts_tg', models.CharField(max_length=30, verbose_name='Телеграм')),
                ('kontakts_vk', models.CharField(max_length=30, verbose_name='Вконтакте')),
                ('kontakts_youtube', models.CharField(max_length=30, verbose_name='Youtube')),
                ('kontakts_habr', models.CharField(max_length=30, verbose_name='habr')),
                ('kontakts_pikabu', models.CharField(max_length=30, verbose_name='Пикабу')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обо мне')),
            ],
            options={
                'verbose_name': 'я',
            },
        ),
    ]
