# Generated by Django 4.1.1 on 2022-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='kontakts_habr',
            field=models.CharField(max_length=100, verbose_name='habr'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='kontakts_pikabu',
            field=models.CharField(max_length=100, verbose_name='Пикабу'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='kontakts_tg',
            field=models.CharField(max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='kontakts_vk',
            field=models.CharField(max_length=100, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='kontakts_youtube',
            field=models.CharField(max_length=100, verbose_name='Youtube'),
        ),
    ]
