# Generated by Django 4.1.1 on 2022-09-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_aboutme_kontakts_habr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'я', 'verbose_name_plural': 'я'},
        ),
    ]
