# Generated by Django 4.1.1 on 2022-09-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_rename_kontakts_habr_aboutme_contakts_habr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='contakts_habr',
            new_name='contacts_habr',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='contakts_pikabu',
            new_name='contacts_pikabu',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='contakts_tg',
            new_name='contacts_tg',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='contakts_vk',
            new_name='contacts_vk',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='contakts_youtube',
            new_name='contacts_youtube',
        ),
    ]
