# Generated by Django 4.1.1 on 2022-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_rename_contakts_habr_aboutme_contacts_habr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='contacts_github',
            field=models.CharField(default='https://github.com/Scryptor', max_length=200, verbose_name='github'),
            preserve_default=False,
        ),
    ]
